name: tensorlib
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - cudatoolkit
  - cudatoolkit-dev
  - openblas
  - gcc=10
  - gxx=10
  - cmake
  - graphviz # optional, to visualize the computational graph
  - pybind11
  - numpy
  - pip
